spring.application.name=ecom
server.port=${APPLICATION_PORT:8080}

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.security.jwt.secret=${Hs256SecretKey:Evb7Mepwi49E8pXiFehyF4cI54+POA9dr1OjtpyhVkc=}

# Eureka configuration
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:8761/eureka/

# GRPC configuration --> the name NOTIFICATION-SERVICE-CLIENT is case sensitive should match with @GRPCClient  annotation in the code
grpc.discovery.enabled=true 
grpc.client.NOTIFICATION-SERVICE-CLIENT.address=discovery:///NOTIFICATION-SERVICE
grpc.client.NOTIFICATION-SERVICE-CLIENT.negotiation-type=plaintext
net.devh.boot.grpc.client.nameresolver.discovery-client.service-metadata-keys=gRPC_port
