spring:
  application:
    name: ecom        # optional, defaults to 'ecom'
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      jakarta:
        persistence:
          schema-generation: # Used to generate the schema creation script
            scripts:
              action: create
              create-target: src/main/resources/schema-creation.sql
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "1"
  security:
    jwt:
      secret: ${Hs256SecretKey:Evb7Mepwi49E8pXiFehyF4cI54+POA9dr1OjtpyhVkc=}
  redis:
    host: localhost
    port: 6379
    timeout: 200ms          # connection + read timeout
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        max-wait: 500ms     # must NOT be -1
      shutdown-timeout: 100ms
  cache:
    # This is the switch to turn on/off caching Can take value like simple,none,redis
    type: none
server:
  port: ${APPLICATION_PORT:8081}
grpc:
  client:
    NOTIFICATION-SERVICE: # this is refered in the code NotificationServiceGRPClient.java
      address: "static://localhost:9090"
      negotiation-type: plaintext
aws: # This is not taken for spring auto config, we are loading iit with config loaders
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY:localadmin}
  secret-key: ${AWS_SECRET_KEY:localadmin}
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000} # Critical for MinIO
    pre-signed-url-expiration-in-seconds: 3600 # in seconds
    buckets:
      product-images: product-images
      product-videos: product-intro-videos