spring.application.name=ecom
server.port=${APPLICATION_PORT:8080}

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.security.jwt.secret=${Hs256SecretKey:Evb7Mepwi49E8pXiFehyF4cI54+POA9dr1OjtpyhVkc=}

# Eureka configuration

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# GRPC configuration --> the name NOTIFICATION-SERVICE is case sensitive should match with @GRPCClient  annotation
grpc.client.NOTIFICATION-SERVICE.address=static://localhost:9090
grpc.client.NOTIFICATION-SERVICE.negotiationType=plaintext
grpc.discovery.enabled=true