spring.application.name=ecom


//hibernateConfigs
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
#spring.datasource.username=postgres
#spring.datasource.password=rcnb1704!
#spring.datasource.driver-class-name =com.postgres.jdbc.Driver
