version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: your-spring-boot-app-image
    container_name: spring_boot_app
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data: