version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
    # Creating a db and user for it.
      POSTGRES_DB: ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sample_password
    # Inside the container it runs on 5432 for outside(local Machine) it is exposed in 5433
    ports:
      - "5433:5432"
    # Volumes are used to store the data in local --> even if the container goes down/deleted the data will be taken from this place , /var/... is WSL path
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  app:
    # build: . --> Docker will build the app container from the Dockerfile located in the current directory.
    build: .
    # build using DockerFile and gives the name "ecom_app"
    image: ecom_app_image
    container_name: ecom_app_container
    restart: always
    depends_on:
      - db
    ports:
      - "9090:8080"
#    inside the container it runs on 8080 for outside(local machine) it is exposed in 9090
volumes:
  pgdata:
